### PR TITLE
update reccommended version of nvidia driver to 396.18 due to compila…

### LINKED ISSUE #10: Systemd failures
Hey
any idea why this is happening with systemd?

```localhost opt # systemctl status modulus@nvidia-390.48.service
● modulus@nvidia-390.48.service - compile kernel modules
   Loaded: loaded (/etc/systemd/system/modulus@.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sun 2019-03-03 06:02:40 UTC; 5min ago
  Process: 14367 ExecStart=/bin/bash -c ${MODULUS_BIN_DIR}/modulus install $(echo nvidia-390.48 | tr '-' ' ') (code=exited, status=1/FAILURE)
  Process: 3377 ExecStart=/bin/bash -c ${MODULUS_BIN_DIR}/modulus compile $(echo nvidia-390.48 | tr '-' ' ') (code=exited, status=0/SUCCESS)
  Process: 3366 ExecStart=/bin/bash -c ${MODULUS_BIN_DIR}/modulus install $(echo nvidia-390.48 | tr '-' ' ') (code=exited, status=1/FAILURE)
  Process: 3297 ExecStart=/bin/bash -c ${MODULUS_BIN_DIR}/modulus download $(echo nvidia-390.48 | tr '-' ' ') (code=exited, status=255)
 Main PID: 14367 (code=exited, status=1/FAILURE)

Mar 03 06:02:40 localhost bash[14367]: depmod: ERROR: openat(//lib/modules/4.19.23-coreos-r1, modules.symbols.tmp, 1101, 644): Read-only file system
Mar 03 06:02:40 localhost bash[14367]: depmod: ERROR: openat(//lib/modules/4.19.23-coreos-r1, modules.symbols.bin.tmp, 1101, 644): Read-only file system
Mar 03 06:02:40 localhost bash[14367]: depmod: ERROR: openat(//lib/modules/4.19.23-coreos-r1, modules.builtin.bin.tmp, 1101, 644): Read-only file system
Mar 03 06:02:40 localhost bash[14367]: depmod: ERROR: openat(//lib/modules/4.19.23-coreos-r1, modules.devname.tmp, 1101, 644): Read-only file system
Mar 03 06:02:40 localhost bash[14367]: depmod: WARNING: could not open /opt/drivers/nvidia/lib/modules/4.19.23-coreos-r1/modules.order: No such file or directory
Mar 03 06:02:40 localhost bash[14367]: depmod: WARNING: could not open /opt/drivers/nvidia/lib/modules/4.19.23-coreos-r1/modules.builtin: No such file or directory
Mar 03 06:02:40 localhost bash[14367]: modprobe: ERROR: could not insert 'nvidia': Unknown symbol in module, or unknown parameter (see dmesg)
Mar 03 06:02:40 localhost systemd[1]: modulus@nvidia-390.48.service: Main process exited, code=exited, status=1/FAILURE
Mar 03 06:02:40 localhost systemd[1]: modulus@nvidia-390.48.service: Failed with result 'exit-code'.
Mar 03 06:02:40 localhost systemd[1]: Failed to start compile kernel modules.```

### PR DESCRIPTION
**Pull request by AnalogJ**
…tion errors on CoreOS stable (with kernel 4.16) - See: https://devtalk.nvidia.com/default/topic/1030082/linux/kernel-4-16-rc1-breaks-latest-drivers-unknown-symbol-swiotlb_map_sg_attrs-/2

fixes #10

### CODE REVIEW

**Review by squat — COMMENTED** [review]
Thanks for the patch, @AnalogJ. Does this successfully fix the issue in your tests?

Two of the CI module compilation tests are failing due to unrelated issues in the semaphore config.

**Comment by AnalogJ** [comment]
Yes it does. After updating the driver version my service runs correctly.

**Comment by squat** [comment]
Thanks, @AnalogJ :) I'm going to sort out the CI infra issues to get master green again.

**Comment by AnalogJ** [comment]
Hey @squat, would it make sense to setup nightly builds using the stable coreos branch developer container? 

I can take a look at implementing that if you're interested.

**Comment by squat** [comment]
I have nightly builds running for nvidia on alpha and beta but not stable and wireguard on beta. I thought these would be enough of a signal though I can definitely add stable.

**Pull request merged**
