### PR TITLE
WIP - Nvidia update and Flatcar linux migration

### PR DESCRIPTION
**Pull request by dippynark**
Picks up from https://github.com/squat/modulus/pull/14

I believe the issue with the filesystem resize is that the Flatcar filesystem doesn't fit inside the 4GB default image size provided as a modulus script input parameter (`-v`) (not 100% sure what is going on, so this may not be correct).

Running what the error suggests gives:
```
# e2fsck -fy "flatcar_developer_container.bin.out"
e2fsck 1.44.5 (15-Dec-2018)
The filesystem size (according to the superblock) is 1572864 blocks
The physical size of the device is 1048576 blocks
Either the superblock or the partition table is likely to be corrupt!
Abort? yes
```

So instead of running the previous `truncate` command I did `resize2fs -M "flatcar_developer_container.bin"` which results in an image of 4.4GB, so I believe the truncate command is reducing the image beyond the end of the filesystem (to 4GB), hence the corruption. As a fix I bumped the `MODULUS_IMAGE_VOLSIZE_GIB` default to 5.

We'll see if CI agrees, Semaphore is having Docker rate limiting issues atm (pinning `koalaman/shellcheck:latest` should help).

I would also think just using `resize2fs -Mf "flatcar_developer_container.bin"` would be better than `resize2fs -f "flatcar_developer_container.bin" "5G"` as it make the image as small as possible - not sure if there are other implications of doing this.

EDIT: @squat I think the next thing is to expose the kernel configuration in the Docker container so that `gzip -cd /proc/config.gz > /usr/src/linux/.config` works -- I don't think the CI definition is included in the repo so will need to be done outside of this PR

### CODE REVIEW

**Comment by squat** [comment]
hi @dippynark thanks for putting so much work into this! I'd like to get this wrapped up soon, since it's been a problem for so long

Regarding your comment about mounting in /proc into the Docker container, I'm not sure this is the problem. Compiling the kernel modules using Docker containers is only one of the isolation strategies modulus supports, and only one of the 3 different tests. TAL at the most recent run from my branch: https://semaphoreci.com/squat/modulus/branches/pull-17-head/builds/1
All three tests fail for the same reason, however, they are using different isolation strategies during compilation:
1. uses chroot inside of a modulus docker container
2. uses a docker container directly on the host
3. uses a chroot directly on the host
I'm curious why /proc wouldn't be available now if this has worked before. Maybe something changed in semaphore ci? I'll SSHing into the semaphore build job to poke around. I'll update this issue :)

Again, thanks to you and @AnalogJ for all of the hard work.

**Comment by squat** [comment]
yes confirmed that something changed in the semaphore VMs. The no longer expose the kernel config at `/proc/config.gz`. They only expose it at `/boot/config-$(uname -r)`. In order to get CI to pass, we need to test on a system that has this file. The options I see are:
1. set up CI on a different provider that does have `/proc/config.gz` 
2. fake the file on Semaphore; we can't gzip this file and bind mount it over /proc because I think procfs doesn't allow this, so we may need to add an option to modulus to read the config from a different location.
Thoughts?

**Comment by dippynark** [comment]
@squat could we bind mount `/boot/config-$(uname -r)` and have a conditional that first tries to use `/proc/config.gz` and then falls back to `/boot/config-$(uname -r)`?

**Comment by AnalogJ** [comment]
Hey @squat 

I actually went a different route (mostly based on concepts in your repo):
- https://github.com/mediadepot/docker-flatcar-developer 
     - docker repo that builds 2 images, one for the basic developer image and another containing the kernel sources for the associated version of Flatcar linux (not the runtime Kernel)
     - this repo has a cron trigger that runs daily to check for new versions of Flatcar in each stream. When a new stable version is detected, 2 new docker images are created and published
 - https://github.com/mediadepot/docker-flatcar-nvidia-driver
     - contains a docker image that is based on the `-sources` version of the flatcar developer image. It clones the Nvidia drivers and compiles it against the Flatcar kernel source, rather than the runtime kernel. This allows me to pre-build the nvidia drivers, rather than having to compile them on my servers. 
- https://github.com/mediadepot/flatcar-forklift
    - is a SystemD service wrapper, similar to your modulus service. However its just doing the following:
         - check for missing drivers
         - docker pull
         - docker cp (to extract the pre-compiled nvidia drivers)
         - the nvidia kernel module is loaded 

It's been working pretty well for me, and its mostly based on concepts from Modulus, so thanks!

**Comment by squat** [comment]
@dippynark 
> @squat could we bind mount /boot/config-$(uname -r) and have a conditional that first tries to use /proc/config.gz and then falls back to /boot/config-$(uname -r)?

This is exactly the route I went (https://github.com/squat/modulus/blob/pull/17/head/modulus#L24)
Now the only thing failing is that the nvidia compilation itself fails https://semaphoreci.com/squat/modulus/branches/pull-17-head/builds/5
```
cc1: some warnings being treated as errors
compilation terminated.
make[2]: *** [/usr/src/linux-5.9.16-coreos/scripts/Makefile.build:283: /tmp/nvidia/NVIDIA-Linux-x86_64-440.64/kernel/nvidia/linux_nvswitch.o] Error 1
In file included from /tmp/nvidia/NVIDIA-Linux-x86_64-440.64/kernel/nvidia/nvlink_linux.c:30:
/tmp/nvidia/NVIDIA-Linux-x86_64-440.64/kernel/common/inc/nv-linux.h: At top level:
/tmp/nvidia/NVIDIA-Linux-x86_64-440.64/kernel/common/inc/nv-linux.h:160:10: fatal error: linux/ioctl32.h: No such file or directory
  160 | #include <linux/ioctl32.h>          /* register_ioctl32_conversion()    */
      |          ^~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
compilation terminated.
make[2]: *** [/usr/src/linux-5.9.16-coreos/scripts/Makefile.build:283: /tmp/nvidia/NVIDIA-Linux-x86_64-440.64/kernel/nvidia/nvlink_linux.o] Error 1
make[2]: Target '__build' not remade because of errors.
make[1]: *** [Makefile:1789: /tmp/nvidia/NVIDIA-Linux-x86_64-440.64/kernel] Error 2
make[1]: Target 'modules' not remade because of errors.
make[1]: Leaving directory '/usr/src/linux-5.9.16-coreos'
make: *** [Makefile:81: modules] Error 2
ERROR: The nvidia kernel module was not created.
```
maybe we can find some hints in @AnalogJ 's repos  :)))))

**Comment by squat** [comment]
ah wait.. it seems the problem is due to this change: https://github.com/squat/modulus/pull/17/files#diff-6aa905bf176b6d2a989a835f4c11c2a61bd8c35268258f17f169ee0755fdc628R331

This should not be here, because it would force the compilation to always match the kernel version of the host. This is _not_ what we want because it prevents us from being able to compile for future versions, e.g. on shutdown for the next OS version so that the modules are ready, or e.g. compiling modules in CI running ubuntu (as we do)

**Comment by squat** [comment]
@dippynark tests are passing for NVIDIA 440.64 @ stable. The tests for beta and alpha fail because NVIDIA seems to not work for kernels > 5.9.12. I am going to merge :rocket: :rocket:

I'm going to do some more exploration to see if I can make a patch to get the module to compile for these newer kernels and add it conditionally to the /nvidia/compile script

Thanks for all of the work, @dippynark @AnalogJ

**Pull request merged**
